---
- name: Ubuntu_MySQL | Install {{ mysql_package }}
  ansible.builtin.apt:
    pkg:
      - '{{ mysql_package }}-server'
      - python3-pymysql
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Ubuntu_MySQL | Enable & start {{ mysql_package }}
  ansible.builtin.systemd_service:
    name: '{{ mysql_package }}.service'
    enabled: true
    state: started

- name: Ubuntu_MySQL | Disallow root login remotely
  ansible.builtin.command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Ubuntu_MySQL | Get list of hosts for the root user.
  ansible.builtin.command: mysql -NBe
    "SELECT Host
    FROM mysql.user
    WHERE User = 'root'
    ORDER BY (Host='localhost') ASC"
  register: mysql_root_hosts
  changed_when: false
  check_mode: false

- name: Ubuntu_MySQL | Update MySQL root password for localhost root account
  ansible.builtin.command:
    mysql -u root -NBe
    "ALTER USER 'root'@'{{ item }}'
     IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}'; FLUSH PRIVILEGES;"
  no_log: true
  with_items: "{{ mysql_root_hosts.stdout_lines | default([]) }}"
  when: mysql_change_root_password and mysql_package == "mysql"
  changed_when: true

- name: Ubuntu_MySQL | Update MariaDB root password for localhost root account
  ansible.builtin.command:
    mysql -u root -NBe
    "SET PASSWORD FOR 'root'@'{{ item }}' = PASSWORD('{{ mysql_root_password }}'); FLUSH PRIVILEGES;"
  no_log: true
  with_items: "{{ mysql_root_hosts.stdout_lines | default([]) }}"
  when: mysql_change_root_password and mysql_package == "mariadb"
  changed_when: true

- name: Ubuntu_MySQL | Copy .my.cnf file with root password credentials.
  ansible.builtin.template:
    src: "root-my.cnf.j2"
    dest: "/root/.my.cnf"
    owner: root
    group: root
    mode: '0400'
  no_log: true
  when: mysql_change_root_password

- name: Ubuntu_MySQL | Get list of hosts for the anonymous user.
  ansible.builtin.command: mysql -NBe "SELECT Host FROM mysql.user WHERE User = ''"
  register: mysql_anonymous_hosts
  changed_when: false
  check_mode: false

- name: Ubuntu_MySQL | Remove anonymous MySQL users.
  community.mysql.mysql_user:
    name: ""
    host: "{{ item }}"
    state: absent
  with_items: "{{ mysql_anonymous_hosts.stdout_lines | default([]) }}"
